### PR TITLE
rules: clarify wording on stonewall setting

### PR DESCRIPTION
**Pull request by adilger**
Also minor cleanups to match the VI4IO text and remove tabs.

### CODE REVIEW

**Review by JulianKunkel — COMMENTED** [review]
I do not like these artificial line breaks they make it more difficult for me to spot differences with git diff.

**Review by johnbent — APPROVED** [review]

**Review by johnbent — APPROVED** [review]

**Review by gflofst — APPROVED** [review]

**Review by gmarkomanolis — APPROVED** [review]

**Comment by adilger** [comment]
@JulianKunkel while there is a minor overhead the first time the line is split, I find it _easier_ to review the changes when the lines are limited in length.  Otherwise, when reviewing `git diff -w` the changed line may be hundreds or thousands of characters long even if only a few characters are different, and it is very difficult to see what has changed.  If the lines are 80 characters long then the "search space" is much smaller since only the 80 characters that have changed need to be compared.  This isn't perfect if there is a multi-line edit, but the displayed multi-line diff is still not worse than if the long-line diff is wrapped across multiple lines.

Also, when viewing changes online in GitHub, it emphasizes the specific parts of the line that have changed within the line itself.  Compare this to the [IO-500 cleanup](https://github.com/IO500/webpage/commit/4abac2b00107681ef26977e2b5600d138de053de) patch which has lines that are so long, like [templates/Pages/bof_isc18.php L46](https://github.com/IO500/webpage/commit/4abac2b00107681ef26977e2b5600d138de053de#diff-71e4e973b635624e7e1be5250b92ce0338cbcfd6010004f5736e5b6994978853R46) and [templates/Pages/bof_isc16.php L25](https://github.com/IO500/webpage/commit/4abac2b00107681ef26977e2b5600d138de053de#diff-c4f90bb984be02b3b1683bd18d44a1cedcc39ebfde0c7479bc3ed6f0540247a9R25), that the changes are not even visible on the screen without scrolling.

**Comment by JulianKunkel** [comment]
That is for me an editor configuration.
I agree that these patches with integrated plots are not optimal.
I find it rather suboptimal to review changes just to figure out that
whitespace has changed.

**Comment by adilger** [comment]
Definitely the patches with long lines due to automatically-generated content are hard to fix, but in the case of plain text that is generated by humans, using shorter lines is not difficult, yet makes reviewing such changes much easier.

In GitHub it is possible to select "Hide whitespace changes" when reviewing the patch, like `git show -w`.  This unfortunately does not hide newly-added line breaks, but does hide the tab->space conversion (since spaces seem to be the default for these files).

I agree that I could have separated the "stonewall = 300" change that Jay requested from the whitespace changes within that file, and I will try to do that in the future.  It would be great if you could approve this change so that we can move on to other things.

**Review by JulianKunkel — APPROVED** [review]

**Comment by adilger** [comment]
This was merged, but I'm not sure why the PR was not closed.

**Pull request merged**
