### PR TITLE
sql: fix AI400X2 system names

### PR DESCRIPTION
**Pull request by adilger**
Per Shuichi Ihara, split the two AI400X2 results into systems named AI400X2-I and AI400X2-II since they are different systems.

### CODE REVIEW

**Review by jeanbez — COMMENTED** [review]
Just to confirm that this change will only reflect in those submissions details. If they require changes in a published list to split the two and appear as two separate entries, we need further updates to ensure that.

**Review by JulianKunkel — APPROVED** [review]

**Review by gflofst — APPROVED** [review]

**Comment by adilger** [comment]
Jean Luca, thanks for the clarification. What are the names of the other tables that need to be updated?

**Comment by jeanbez** [comment]
@adilger we have one table for each released list (e.g., `list_isc22_io500`, `list_isc22_10node`) that have three required fields (`listing_id`, `submission_id`, and `score`). We need to modify those as well, and once that is done, recreate the table view that aggregate all. If you know what changes need to be done, I can do that change and document the process so we have a reference for future updates.

**Comment by adilger** [comment]
@jeanbez the goal here is to deduplicate the two submissions from Shuichi in the ISC'22 list. They were considered duplicates and only one shown in the 10-node and full lists, but they were actually two separate systems - a one-server system and a two-server system. 

As in this PR, the AI400X2-II system had score 183.34, and the AI400X2-I system had score 107.04.  The -II system is in the ISC'22 full listing now, but the -I system is missing and would be ranked 44.  Similarly, the -I system is missing from the 10-node ISC'22 list, where is would be ranked 32.

I could probably figure out the SQL for adding them to those lists, but have no idea how to fix the redo of the list (maybe write a shell script that generates SQL commands that increment all of the current entries' rank by one?). Probably safer if you do it.

**Comment by jeanbez** [comment]
@adilger I lost track of this last update. If that is still needed would you mind open another issue so we can track and fix this asap?

**Comment by adilger** [comment]
I updated the system name in the one list, but did not actually update the system name in every list. This is less critical since the new lists have the right names and only a few older ones are still inconsistent.

**Pull request merged**
