### PR TITLE
Configure approval of database updates

### PR DESCRIPTION
**Pull request by jeanbez**
As previously discussed, this commit will configure a GitHub Action to check for any new or modified files in `/sql` folder and execute it after the approval of the committee. With this change we will be able to not only track any changes to the database, but also wait for approval on new modifications. 

I already included a dump of the current DB and marked it as run.

### CODE REVIEW

**Review by JulianKunkel — APPROVED** [review]

**Review by adilger — APPROVED** [review]

**Review by adilger — APPROVED** [review]

**Review by gmarkomanolis — APPROVED** [review]

**Review by adilger — CHANGES_REQUESTED** [review]
Jean Luca, looking at this dump, it still appears that it is ordered by the current IO500 ranking on the main list, and a later dump when new results are added will have a different ranking, causing *every* line in the dump to be updated:

    +INSERT INTO `submissions` (`id`, `release_id`, `information_system`, `information_institution`, ... )
     VALUES(1, 6, 'Wolf', 'Intel',  ...);
    +INSERT INTO `submissions` (`id`, `release_id`, `information_system`, `information_institution`, ...)
     VALUES(2, 6, 'Wolf', 'Intel', ...);

Is it possible to order the database by submission date before dumping it, so that the ordering of the dump is independent of the ranking?

Also, I don't think it makes sense to have the date in the filename for the `io500-db.sql` file, since we would want to update this in-place in Git, and let Git track the changes/dates itself, rather than getting a new dump of the database file each time.  The database dump is currently 1MB for 474 entries (~2.5KB/entry).  Growing the Git repo linearly with entries is fine, but we don't want it growing by the product of the number of entries and modifications over time if it were stored in a separate file for each backup.

**Comment by jeanbez** [comment]
@adilger Yes, the dump is ordered according to when the entries were added in the database, i.e., the `id` field. 

However, it was *not* the idea to have a new full dump every time. The purpose of this pull request was that new records and modifications in the database are pre-approved by the committee (i.e., the SQL that should be run in the production database is first approved) before being persisted. Hence, for new submissions, we will have only those new entries in a new file in the `sqls` directory. If we need to modify something, the file will have just that update statement. You can check this example to have a better idea: 

https://github.com/IO500/webpage/pull/93/files#diff-916d3342cd704477338e5185516f5c7bfd4f53aceed9aa5db537e54e3a0f6168

Julian asked to have a record with the database's initial state, which is why I included the io500-db file and marked it as already run. We can define a naming standard if you prefer, but that does not have any major implications.

On the other hand, if the idea is to have some sort of shadow file for backup purposes, after every list release, then it is another thing for us to do and it has nothing to do with this pull request.

**Comment by adilger** [comment]
@jeanbez I guess I was confused because the order in the "new" SQL database has no relation to the order in which the entries were originally submitted to VI4IO. It seems like they were added in approximately the order they were ranked for the SC'20 list. 

I guess this is fine, so long as the ID used to order `mysqldump` never changes.  If I was really pedantic (which I try really hard not to be), I would repopulate the database in the original submission order, since that is what will be used for new records going forward, but there is no compelling reason to do that.

**Review by adilger — APPROVED** [review]

**Review by JulianKunkel — APPROVED** [review]
Good approach!

**Pull request merged**
